# Generated by Django 2.2 on 2021-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Accesories', 'Accesories')], max_length=2),
        ),
    ]
