# Generated by Django 2.2 on 2021-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210217_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'Phone'), ('L', 'Laptop'), ('A', 'Accesories')], max_length=2),
        ),
    ]
